name: docker-publish.yml
on: [push]
jobs:
  publish-ur3-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: |
          docker build -t ur3:noetic ./
          docker run -p 6080:80 -p 5900:5900 -e VNC_PASSWORD=vncpassword --rm -it ur3:noetic
        
